PHP 8 compatibility
10up/simple-local-avatars pull request #103
Opened 2022-03-23 14:39 UTC by faisal-alvi

### Description of the Change

Upgrade the plugin to be compatible with the least supportive PHP v5.3 up to the PHP v8.1

### Verification Process

Make sure the Github actions are passing. Also, test the full plugin functionalities. 

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Security - Plugin made compatible up to PHP 8.1

### Credits

Props @faisal-alvi

2022-03-28 10:01 UTC, Sidsector9 requested changes

2022-03-28 10:01 UTC, Sidsector9 commented on .github/workflows/php-compatibility.yml
> +        php: [ '5.6', '7.0', '7.4', '8.0', '8.1' ]
You can remove this matrix here and from the places where it is used. See this [Slack post](https://10up.slack.com/archives/C84M9AA06/p1648460113851159) for more details.

2022-03-28 10:07 UTC, Sidsector9 requested changes

2022-03-28 10:07 UTC, Sidsector9 commented on .github/workflows/lint.yml
> +          tools: prestissimo, composer:v2
`prestissimo` is not necessary if you're using composer v2.
Read more here: https://github.com/hirak/prestissimo#announcement-composer-2-is-now-available

2022-03-28 10:08 UTC, Sidsector9 requested changes

2022-03-28 10:08 UTC, Sidsector9 commented on .github/workflows/php-compatibility.yml
> +          tools: prestissimo, composer:v2
`prestissimo` is unnecessary if we're using composer v2,
[Refer to this](https://github.com/hirak/prestissimo#announcement-composer-2-is-now-available) for more details.

2022-03-28 10:12 UTC, Sidsector9 requested changes

2022-03-28 10:12 UTC, Sidsector9 commented on .github/workflows/lint.yml
> +        uses: chekalsky/phpcs-action@v1
We're already using [10up/phpcs-composer](https://github.com/10up/phpcs-composer) in the project. Would be great to keep tools consistent.

Refer [to this section](https://docs.google.com/document/d/1r6WSXn22bOYfotDd9oyqf_CPsPXBGK2M1TfKDeKQ7Ew/edit#heading=h.mhv3eyi68ryb) for more details.

2022-04-15 09:30 UTC, faisal-alvi commented
@Sidsector9 just a reminder, this is ready for review.

2022-04-15 13:48 UTC, Sidsector9 approved these changes

2022-04-16 06:52 UTC, merged