Cypress Setup for E2E testing
10up/simple-local-avatars pull request #115
Opened 2022-04-25 11:35 UTC by faisal-alvi

### Description of the Change

Cypress tests setup with the help/use of https://github.com/10up/cypress-wp-setup/ && https://github.com/10up/cypress-wp-utils.

Closes #111.

### Alternate Designs

n/a

### Possible Drawbacks

n/a

### Verification Process

Make sure all tests added are running without fail.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Added - Cypress tests for E2E testing.

### Credits

Props @faisal-alvi @vikrampm1

2022-05-25 06:49 UTC, Sidsector9 requested changes

2022-05-25 06:49 UTC, Sidsector9 commented on tests/cypress/integration/avatars-migration.test.js
> +describe('Check if avatar migration works', () => {
Although the title implies we are testing if migration works, the test itself doesn't perform any migration.
I think we can change it to:

```js
describe( 'Avatar migration', () => {} )
```
As the context for this test is migration of avatars.

And the test title can be set to:

```js
it( 'Test no migration from WP User Avatar' );

2022-05-25 06:49 UTC, Sidsector9 commented on tests/cypress/integration/set-avatar.test.js
> +    it('Can admin upload, crop and select local avatar?', () => {
As we're not testing cropping in this test, it can be removed from the title.

2022-05-27 10:16 UTC, faisal-alvi commented on tests/cypress/integration/set-avatar.test.js
> +    it('Can admin upload, crop and select local avatar?', () => {
Actually, we are, the cropping action runs so fast that we don't see it:

![sla-pr-115](https://user-images.githubusercontent.com/25176325/170680638-a9ebb5da-d899-4676-ada5-42237e256d5b.gif)

Please let me know if this is not what you expected.

2022-05-30 04:36 UTC, Sidsector9 commented on tests/cypress/integration/set-avatar.test.js
> +    it('Can admin upload, crop and select local avatar?', () => {
brilliant! 👍

2022-05-30 04:36 UTC, Sidsector9 approved these changes

2022-05-30 10:08 UTC, merged