Fix thumbnail urls for network configured avatars
10up/simple-local-avatars pull request #125
Opened 2022-05-09 07:45 UTC by vladolaru

### Description of the Change

After generating a non-existent thumbnail size for an avatar in the `Simple_Local_Avatars::get_simple_local_avatar_url()@L336` method, the current logic transforms the destination file path to a URL by replacing the current blog `$upload_path['basedir']` with `$upload_path['baseurl']`. 

This works fine for all situations except when avatars are configured at the network level, since those avatars use the `uploads` directory (`wp-content/uploads`) as a basedir, not the site-specific directory (e.g. `wp-content/uploads/sites/5/`). This is why the destination file path doesn't get converted into a URL, and the plugin ends up caching the full path for that thumbnail size.

My solution is to test for this specific case, and properly transform the path into a URL.

Closes #124 

### Alternate Designs

Not the case.

### Possible Drawbacks

None that I can imagine.

### Verification Process

I have checked both with our themes (@pixelgrade) and with the standard core themes. Since the logic is additional to the existing one, without modifying the existing logic, the changes are safe.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

Fixed - Broken avatar URLs for network-configured shared avatars with non-standard thumbnail sizes.

### Credits

Props @vladolaru

2022-05-13 10:56 UTC, faisal-alvi requested changes
@vladolaru Resolves the issue perfectly, thanks for the work! Just minor suggestions added below, then it'll be ready for merge.

2022-05-13 10:56 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +							// Transform the destination file path into URl.
```suggestion
							// Transform the destination file path into URL.
```

2022-05-13 10:56 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +							if ( false !== strpos( $dest_file, $upload_path['basedir'] ) ) {
```suggestion
							if ( strpos( $dest_file, $upload_path['basedir'] ) ) {
```

2022-05-13 10:56 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +							} else if ( is_multisite() && false !== strpos( $dest_file, ABSPATH . 'wp-content/uploads' ) ) {
```suggestion
							} else if ( is_multisite() && strpos( $dest_file, ABSPATH . 'wp-content/uploads' ) ) {
```

2022-05-13 14:05 UTC, vladolaru commented
Thanks. I've accepted the suggestions.

2022-05-13 14:07 UTC, vladolaru commented
Actually, no :) We need to strictly compare with `false` since `strpos()` returns `0` when the needle is found at the beginning of the string. And `0` evaluates to false, not true when converted to bool.

2022-05-16 09:05 UTC, faisal-alvi approved these changes
🚀

2022-05-16 09:06 UTC, merged