bbPress - make sure the button to remove the avatar works
10up/simple-local-avatars pull request #133
Opened 2022-05-26 10:18 UTC by foliovision

### Description of the Change

When the user avatar is stored, the "Delete local avatar" button on bbPress edit page does not work.

The button is actually a simple link with the `user_id={ID}` and and `action=remove-simple-local-avatar`.

This improvement makes sure it's processed for bbPress edit profile page.

### Alternate Designs

It might be better to adjust admin_enqueue_scripts() to work on bbPress edit profile page, it would also use the nonce that way.

### Possible Drawbacks

It's missing the nonce security.

### Verification Process

The "Delete local avatar" on the bbPress profile editing is now able to delete the stored avatar.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Fixed - avatar removal on bbPress profile edit page

### Credits

Props @foliovision

2022-05-27 12:46 UTC, faisal-alvi requested changes
@foliovision thanks for the work here. However, IMO we can adopt another more robust solution here.

> It might be better to adjust admin_enqueue_scripts() to work on bbPress edit profile page, it would also use the nonce that way.

Agree with this statement. The bbPress loads the same "edit profile" template on the FE.

![image](https://user-images.githubusercontent.com/25176325/170701779-0973557a-209b-4e8c-a1e6-5a2ca8c50788.png)
[image link](https://www.screencast.com/t/ONhUmRb3)

But currently, the SLA plugin does not perform any JS actions at the FE side which is causing the issue here. So instead of handling the page load action, we should move the "Delete action" JS code to a separate file and load that file on both sides (BE & FE).

@jeffpaul @dkotter any thoughts on this?

2022-05-27 17:09 UTC, dkotter commented
Is the only thing not working here the delete portion? And is the code we need to handle this the exact same as the code we use on the admin side? If so, I'm fine with loading that on the FE if on a bbPress edit profile page.

Any downside to just loading the entire JS file instead of having to abstract portions out? Seems like there's other things we'll need as well, like the user ID and nonce, where we could see if bbPress fires an action when on an edit profile page and hook in our same `admin_enqueue_scripts` method.

2022-05-30 06:58 UTC, foliovision commented
I agree it would be better to include all the same scripts as when editing the profile in wp-admin and then the same Ajax should work.

Thanks,
Martin

2022-05-30 10:31 UTC, faisal-alvi commented
@dkotter 
> Is the only thing not working here the delete portion?

so far, yes.


> And is the code we need to handle this the exact same as the code we use on the admin side? If so, I'm fine with loading that on the FE if on a bbPress edit profile page.

yes, the code is same.

> Any downside to just loading the entire JS file instead of having to abstract portions out? Seems like there's other things we'll need as well, like the user ID and nonce, where we could see if bbPress fires an action when on an edit profile page and hook in our same admin_enqueue_scripts method.

We can load the entire JS file only on the bbPress edit profile page but most of the JS code will be unnecessarily loaded as it is required only for the BE side.

2022-06-03 11:48 UTC, faisal-alvi commented
Closing after #134.

2022-06-03 11:48 UTC, closed without merging