Enhancement/148 | Expose hooks for "avatar updated" and "avatar deleted"
10up/simple-local-avatars pull request #149
Opened 2022-08-31 12:12 UTC by t-lock

### Description of the Change

Exposes two hooks, `simple_local_avatar_updated` and `simple_local_avatar_deleted`. These hooks allow theme developers or other plugin developers to react to changes in local avatars in a consistent and precise way. 

Example use cases include:
- sharing user avatars with external services such as chat or forum add-ons
- developing front-end flows for editing user profiles
- any use case adjacent to user management

Closes #148 

### Changelog Entry
> Added - Two hooks, `simple_local_avatar_updated` and `simple_local_avatar_deleted`

### Credits
@t-lock

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-08-31 12:14 UTC, t-lock commented
I have not written a test scenario for this, but its totally understandable if that is a prerequisite for considering this PR. 

Thanks for your work on this plugin, excited to be able to pull the upstream back into my project if the team agrees this functionality is worth including in Simple Local Avatars.

2022-08-31 12:21 UTC, t-lock commented
Also, I wasn't sure where to add documentation, apologies if that was something obvious I missed. Happy to add if someone can point me in the right direction.

2022-09-02 09:31 UTC, faisal-alvi requested changes
A few PHPCS issues.

2022-09-02 09:31 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +		do_action("simple_local_avatar_updated", $user_id);
```suggestion
		do_action( 'simple_local_avatar_updated' , $user_id );
```

2022-09-02 09:31 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +			do_action("simple_local_avatar_deleted", $user_id);
```suggestion
			do_action( 'simple_local_avatar_deleted', $user_id );
```

2022-09-02 09:32 UTC, faisal-alvi commented
@dkotter Code LGTM, any feedback from your end?

2022-09-02 09:33 UTC, faisal-alvi approved these changes, later dismissed

2022-09-02 15:15 UTC, dkotter requested changes

2022-09-02 15:15 UTC, dkotter commented on includes/class-simple-local-avatars.php
> +		do_action( 'simple_local_avatar_updated' , $user_id );
I know we don't strictly follow this currently in this plugin but ideally any hooks we add should have documentation with them, see https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters. Here's an example in this plugin: https://github.com/10up/simple-local-avatars/blob/develop/includes/class-simple-local-avatars.php#L429.

If that could be added to this action and the other one, that would be great

2022-09-05 06:27 UTC, t-lock commented
@dkotter

>If that could be added to this action and the other one, that would be great

Inline documentation added. Note: I added `@since 2.6.0` assuming that this would be included in the next release and it looks like the project isn't releasing 2.x.x minor versions. 

Thanks!

cc @faisal-alvi

2022-09-06 19:44 UTC, dkotter approved these changes

2022-09-06 19:51 UTC, merged