Fix: Non admin can not crop avatar
10up/simple-local-avatars pull request #155
Opened 2022-09-22 10:17 UTC by jayedul

### Description of the Change

In this pull request we've just unregistered all the `setup_theme` action hook at application runtime during ajax call only when it is a crop request. As I debugged backtrace, I found this hook execution  ([https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L549](https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L549)) exits somewhere in case of non admin users. 

I definitely agree it's a very important hook, but as long as we are dealing with only image crop request, so I believe here's nothing to do with theme related stuffs. That's why cleared the hook for the crop request only. 

The issue description meant to integrate another crop tool other than the core one. But that would add more dev stacks. So 
 before proceeding new stacks, this pull request just proposes a simpler fix for the original issue #141 
If it doesn't seem an appropriate solution, then no issue to adopt a new crop tool. 

Closes #150 and #141 

### How to test the Change

1. Go to user edit screen as like as you do from admin account
2. Go to avatar section and click the button `Choose From Media Library` 
3. Select Avatar and Crop
4. Crop a portion as your wish
5. Click Crop button
6. Previously this is where you faced the error, but now it should save as expected. 

### Changelog Entry
> Fix: Non admin can not crop avatar

2022-09-23 16:30 UTC, faisal-alvi requested changes

2022-09-23 16:30 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +		}
```suggestion
		// Fix: An error occurred cropping the image (https://github.com/10up/simple-local-avatars/issues/141).
		if ( isset( $_POST['action'] ) && 'crop-image' === $_POST['action'] && is_admin() && wp_doing_ajax() ) {
			add_action( 'plugins_loaded', function () {
				remove_all_actions( 'setup_theme' );
			} );
		}
```

2022-09-23 16:34 UTC, faisal-alvi approved these changes
@jayedul this is awesome! Working fine!

@dkotter Code LGTM but would like to know your opinion too before merging.

2022-09-26 21:46 UTC, dkotter commented
So if I'm following correctly, the crop tool we're currently using is also used within the customizer and it's limited there to only work for admins, correct?

If so, my concern here is that it seems with the changes here, we would also allow non-admin users the ability to crop within the customizer (though I haven't tested that). If that is the case, is there some way to fix that? For instance, could we add some unique data to our crop request that we can look for and only remove the `setup_theme` hook in that case? That way we can be sure this will only impact crop requests coming from this plugin.

2022-10-10 10:43 UTC, faisal-alvi commented
@dkotter Only users with the "customizer" cap can access the customizer area. And as per the [Roles and Capabilities](https://wordpress.org/support/article/roles-and-capabilities/) doc, the "customize" cap is only with the Super Admins and Administrators user roles. I assume this resolves your concern.

2022-11-14 10:19 UTC, faisal-alvi commented
@dkotter any thoughts on my previous comment?

2022-11-18 18:10 UTC, dkotter commented
> @dkotter any thoughts on my previous comment?

@faisal-alvi Okay, I think we're probably good to go here then. Still makes me a little wary but as long as we've tested with different account levels and haven't seen any issues with users having access they shouldn't have, should be good to go

2022-11-28 06:31 UTC, faisal-alvi commented
I've tested again and the "Appearance > Customize" is only accessible for the users with the "customizer" cap. And only admins and super admins have that cap.

2022-11-28 06:31 UTC, faisal-alvi approved these changes

2022-11-28 06:31 UTC, merged