Cypress integration migrated to 11+
10up/simple-local-avatars pull request #172
Opened 2022-12-07 09:28 UTC by jayedul

### Description of the Change
Cypress integration migrated to 11+

Closes #166 

### How to test the Change
- Install NPM dependencies
- Run `npm run cypress:run` to test without GUI
- Run `npm run cypress:open` to test with GUI
- Check if tests pass successfully

### Changelog Entry

> Changed - Cypress integration migrated to 11+

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2022-12-07 10:11 UTC, faisal-alvi commented
@jayedul seems like the Cypress tests are [failing](https://github.com/10up/simple-local-avatars/actions/runs/3637566144/jobs/6138721048) in the pipeline, can you please check?

2022-12-07 12:56 UTC, faisal-alvi requested changes
@jayedul thanks for the work. Other than checking the GitHub action for cypress, I have left minor suggestions below, please have a look.

2022-12-07 12:56 UTC, faisal-alvi commented on .gitignore
> +tests/cypress/downloads
A new line at EOF would be nice.

2022-12-07 12:56 UTC, faisal-alvi commented on tests/cypress/config.config.js
> +      __dirname+'/integration/*.test.js',
```suggestion
    specPattern: __dirname+'/integration/*.test.js',
```

2022-12-07 12:56 UTC, faisal-alvi commented on tests/cypress/integration/admin.test.js
> +        cy.get("#deactivate-simple-local-avatars, tr[data-slug=simple-local-avatars] .deactivate a").click();
Seems like a proper indention is required. Please make sure whatever we decide to use, whether its spaces or tabs, its applied in all other test files for consistency purposes.

2022-12-08 07:53 UTC, jayedul commented
> @jayedul seems like the Cypress tests are [failing](https://github.com/10up/simple-local-avatars/actions/runs/3637566144/jobs/6138721048) in the pipeline, can you please check?

I'm wondering if the tests used to pass before. 
This test sequence selects first images in the media library and sets as avatar. Locally it works as there are images available. Probably it can't find any image here since Github action sets up totally new WordPress environment. 

Any suggestion?

2022-12-08 14:56 UTC, jayedul commented
> @jayedul seems like the Cypress tests are [failing](https://github.com/10up/simple-local-avatars/actions/runs/3637566144/jobs/6138721048) in the pipeline, can you please check?

Now all tests pass perfectly.

2022-12-09 10:52 UTC, faisal-alvi commented on tests/cypress/support/commands.js
> +import 'cypress-file-upload';
@jayedul  can you please let me know why is this used here?

2022-12-09 11:27 UTC, faisal-alvi commented on tests/cypress/integration/admin.test.js
> +        cy.get("#deactivate-simple-local-avatars, tr[data-slug=simple-local-avatars] .deactivate a").should("be.visible");
We should utilize the Cypress Utils Library and use the `activatePlugin` and `deactivatePlugin` commands.

* https://github.com/10up/cypress-wp-utils/blob/trunk/src/commands/activate-plugin.ts
* https://github.com/10up/cypress-wp-utils/blob/trunk/src/commands/deactivate-plugin.ts

2022-12-12 07:25 UTC, jayedul commented on tests/cypress/support/commands.js
> +import 'cypress-file-upload';
Otherwise the test exits with an error `attachFile is not function`. It looks like updated Cypress requires manually importing the package.

2023-01-06 14:22 UTC, faisal-alvi commented
@jayedul can you please resolve the conflicts?

2023-01-11 15:58 UTC, faisal-alvi approved these changes
@jayedul Thank you for your efforts. 🚀

2023-01-11 15:58 UTC, merged