Added GH Actions summary
10up/simple-local-avatars pull request #174
Opened 2022-12-07 12:25 UTC by faisal-alvi

### Description of the Change
This PR utilizes [the new Markdown support](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) of GH Actions summary (suggested by @jeffpaul) to include the test result in the job summary: https://github.com/10up/cypress-wp-utils/actions/runs/2319016114

To generate the markdown report, this PR uses `mochawesome` reporter. The reporter generates JSON and HTML reports. The report is pretty and solid:

![image](https://user-images.githubusercontent.com/5423135/168274023-67927a1e-5901-4a54-9169-0fdd76c382a7.png)

Closes #158

### How to test the Change

Check the GitHub Action, it should display the Cypress test result summary.

### Changelog Entry
> Added - A GH Actions summary

### Credits

Props @faisal-alvi @jeffpaul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-12-09 14:58 UTC, iamdharmesh requested changes
I think we have to add `if: ${{ always() }}` to the **Update summary** step otherwise it will only run when the E2E test succeeds and will be skipped for test failures.

2022-12-09 14:58 UTC, iamdharmesh commented on .github/workflows/cypress.yml
> +    - name: Update summary
```suggestion
    - name: Update summary
      if: ${{ always() }}
```

2022-12-12 16:08 UTC, iamdharmesh approved these changes
Thanks a lot for adding this @faisal-alvi. LGTM 🚀

2022-12-12 16:14 UTC, merged

2022-12-22 22:10 UTC, jeffpaul commented
@10up/open-source-practice I'd love to see this similarly replicated across our other projects as well as a note on how to do so for future projects added to the Open Source Best Practices... please and thanks!