Local avatar delete-remove functionality added
10up/simple-local-avatars pull request #180
Opened 2022-12-14 09:02 UTC by jayedul

### Description of the Change
From now on, users will see a new button to disassociate avatar rather than deleting permanently since there's a possibility of using the avatar image elsewhere. 

Closes #41 

### How to test the Change

- Login to a non-admin user account that has has no `upload_files` capability
- Go to profile edit page in WP dashboard
- Set a new avatar
- Click delete, it should delete file from the file system
- Set a new avatar again
- This time just remove, it should disassociate the image as avatar, however you should find the image still in the file system

### Changelog Entry

> Added - Avatar removal feature to disassociate images only instead of deleting from file syste,

### Credits

Props @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-01-09 13:41 UTC, faisal-alvi requested changes
@jayedul thank you for working on this.

1. I have tested and seems like when we select the image, it does not show the Remove button for `upload_files` cap users.

![sla-180](https://user-images.githubusercontent.com/25176325/211320924-6d37b3c0-8a7b-407d-99cd-8dc49f264e83.gif)

And when the avatar is removed/deleted, we don't get back the "Choose from media library" button.

2. Can you please let me know why is the `package-lock.json` is changed?
3. Also requested a few changes inline, please have a look.

2023-01-09 13:41 UTC, faisal-alvi commented on assets/js/simple-local-avatars.js
> +		var button_wrapper = $(this).parent();
Should we use `const` instead of `var`?

2023-01-09 13:41 UTC, faisal-alvi commented on assets/js/simple-local-avatars.js
> +			permanent_delete: $(this).attr('id') === 'simple-local-avatar-remove',
This is confusing, can we please use the word "-delete" instead of "-remove", to match it with what we show on front side?

2023-01-09 13:41 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +								$has_local_avatar = ! empty( $old_avatars ) && ! empty( $old_avatars['media_id'] );
Vertical alignment is required.

2023-01-09 13:41 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +										Delete or remove existing avatar to set a new one.
Please make the string translatable.

2023-01-12 19:02 UTC, jayedul commented
@faisal-alvi 
Eventually I noticed there are some inconsistent functional flow. Worked on those little bit. Now the feature should work as expected. Please let me know if still need more fix.

2023-01-13 14:14 UTC, faisal-alvi requested changes
@jayedul thanks for the fixes. The remove and delete buttons are now displaying as expected. However, I have tested again and found a few more things to share, please check the following points.

1. When we hit the Delete button, it does not delete the uploaded images from the file system and we still see the image available under the Media > Library, it still keeps a few (size) versions of the image. Please check the video.

https://user-images.githubusercontent.com/25176325/212338142-ff6ef254-71a0-4f38-a941-ac3bfd46aa33.mp4

2. While testing, I felt that we should add a prompt dialog box when the user clicks the Delete button, the same as we see in the core.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/25176325/212339286-afb90fd7-6479-42f9-b128-da141580adc8.png">

This will be helpful to make sure that users know the difference between two buttons and that they don't get confused.

3. Please add a gap between the buttons and the text above them.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/25176325/212340066-ce59a8a2-bf95-4745-93a4-ff01e8eda41e.png">

4. I feel that we should add more document comments (not just above this PR's code, but in the whole class file) so that we/anyone knows what's happening. This is just an opinion, you can skip this for now. :)

5. Please also check a few inline comments.

2023-01-13 14:14 UTC, faisal-alvi commented on assets/scss/simple-local-avatars.scss
> +		.sla-avatar-upload, .sla-avatar-choose{
Please add a space after `{` on line 1 and 3.

2023-01-13 14:14 UTC, faisal-alvi commented on assets/js/simple-local-avatars.js
> +import '../scss/simple-local-avatars.scss';
Why are we importing the SCSS file inside the JS file?

2023-01-13 14:14 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +					// derive the path for the file based on the upload directory
```suggestion
					// Derive the path for the file based on the upload directory.
```

2023-01-20 08:56 UTC, jayedul commented on assets/js/simple-local-avatars.js
> +import '../scss/simple-local-avatars.scss';
This way we get compiled css file in `dist` directory.

2023-01-20 09:04 UTC, faisal-alvi commented on assets/js/simple-local-avatars.js
> +import '../scss/simple-local-avatars.scss';
We should add it as a new entry in the config so we get its compiled version in `dist`.

https://github.com/10up/simple-local-avatars/blob/65fa58eaa2d309b9b2ceec76c97b1d54be400c23/webpack.config.js#L10-L12

2023-03-07 08:12 UTC, faisal-alvi requested changes

2023-03-07 08:12 UTC, faisal-alvi commented on assets/js/simple-local-avatars.js
> +		if($(this).data('alert') && !window.confirm($(this).data('alert'))) {
```suggestion
		if ($(this).data('alert') && !window.confirm($(this).data('alert'))) {
```

2023-03-07 08:12 UTC, faisal-alvi commented on includes/class-simple-local-avatars.php
> +								<a href="<?php echo esc_url( $remove_url ); ?>" class="button item-delete submitdelete deletion" id="simple-local-avatar-delete" data-alert="<?php echo esc_attr__( 'Are you sure to delete the
```suggestion
								<a href="<?php echo esc_url( $remove_url ); ?>" class="button item-delete submitdelete deletion" id="simple-local-avatar-delete" data-alert="<?php echo esc_attr__( 'Are you sure that you want to permanently delete the image?', 'simple-local-avatars' ); ?>">
```

2023-03-07 08:14 UTC, faisal-alvi approved these changes
@jayedul thanks for the work, LGTM!

2023-03-07 08:27 UTC, faisal-alvi commented
@jayedul During testing, I observed that when someone permanently deletes an image, if anyone else is using the same avatar, their avatar will switch to the default avatar, which may lead to confusion among users. Just wanted to bring it to everone's attention. cc: @dkotter

2023-03-14 14:24 UTC, dkotter commented
@faisal-alvi @jayedul If I'm following correctly, the `Delete` button is an existing feature within this plugin but it wasn't actually deleting the image fully, is that correct? And this PR fixes that as well as adds a `Remove` button?

2023-03-14 15:22 UTC, jayedul commented
@dkotter Exactly. 

@faisal-alvi To avoid confusion, I think it will be better show only own uploaded images to select avatar from. So, no way to use same image by multiple user. Then deletion will be safe.

2023-03-22 22:08 UTC, dkotter commented
@jayedul @faisal-alvi @jeffpaul Apologies for not flagging things sooner but the more I think through things here, the more I think we may have gone further then what is actually needed here.

Reading through the [issue](https://github.com/10up/simple-local-avatars/issues/41) again, the problem being reported is they want a way to remove an avatar image from a specific user without having to delete that image all together. But that functionality is already in place.

I think the confusion here is the button we output says `Delete local avatar` but it doesn't actually delete the image from what I can tell, it just removes that image from being the user's avatar.

I could see having actual delete functionality to be useful in some scenarios but as @jayedul as already mentioned, you could end up in a situation where someone deletes an image that is used elsewhere, unless we lock down images to the specific user.

For a plugin that we consider stable, I guess my opinion here is that we don't need to add true deletion functionality at the moment. I'd suggest either leaving things as they are or updating the button text to say `Remove local avatar`, so it's more clear what the button does.

2023-03-23 08:52 UTC, faisal-alvi commented
@dkotter, thanks for the feedback. I agree with you. For now, we can update the button text to say `Remove local avatar`. We can use the code from this PR in the future if required to add permanent delete functionality.

2023-03-24 09:09 UTC, faisal-alvi commented
Closing this in favor of #208

2023-03-24 09:09 UTC, closed without merging