Support user objects
10up/simple-local-avatars pull request #193
Opened 2023-01-30 16:57 UTC by mattheu

### Description of the Change
It is expected that I can pass `WP_User` object to [`get_avatar`, as is documented](https://developer.wordpress.org/reference/functions/get_avatar/). But this does not work because `get_user_id` in `Simple_Local_Avatars` does not handle this case. 

Closes #192

### How to test the Change
```
$user = wp_get_current_user();
echo get_avatar( $user );
```

### Changelog Entry

> Fixed - Support passing `WP_User` to `get_avatar`.

### Credits
Props @mattheu

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-01-30 18:13 UTC, mattheu commented
I'm not so familiar with WP_Mock, but I've made some changes so that I can mock a WP_User object. Please advise if there is a better way to do this. Thanks.

2023-02-02 13:51 UTC, faisal-alvi requested changes
Minor spacing fixes

2023-02-02 13:51 UTC, faisal-alvi commented on tests/phpunit/SimpleLocalAvatarsTest.php
> +		$user->display_name = 'TEST_USER';
```suggestion
		$user               = Mockery::mock( WP_User::class );
		$user->ID           = 1;
		$user->display_name = 'TEST_USER';
```

2023-02-02 13:51 UTC, faisal-alvi commented on tests/phpunit/SimpleLocalAvatarsTest.php
> +		$user->ID = 1;
```suggestion
		$user     = Mockery::mock( WP_User::class );
		$user->ID = 1;
```

2023-02-02 13:51 UTC, faisal-alvi commented on tests/phpunit/SimpleLocalAvatarsTest.php
> +		$post->post_author = 1;
```suggestion
		$post              = Mockery::mock( WP_Post::class );
		$post->post_author = 1;
```

2023-02-02 13:51 UTC, faisal-alvi commented on tests/phpunit/SimpleLocalAvatarsTest.php
> +		$comment->user_id = '1';
```suggestion
		$comment          = Mockery::mock( WP_Comment::class );
		$comment->user_id = '1';
```

2023-02-02 13:52 UTC, faisal-alvi commented
@mattheu Awesome! thank you for working on this.

✅  Checked the following code and the avatar works well in the PR branch. Can you please just make those small spacing fixes and we will be good to go!

```
echo '<h1>WORKS</h1>';
$user = wp_get_current_user();
echo get_avatar( $user->ID );

echo '<h1>DOES NOT WORK</h1>';
$user = wp_get_current_user();
echo get_avatar( $user );
```
---
in `develop`:

![image](https://user-images.githubusercontent.com/25176325/216328226-ab3fcc65-64e2-4e3b-b9e8-1f62d88a9029.png)


in this PR:

![image](https://user-images.githubusercontent.com/25176325/216328136-19caea4b-3e3c-45ca-99ed-54b551b33ca6.png)

2023-02-02 14:10 UTC, mattheu commented
Thanks. Suggestions applied.

2023-02-03 06:20 UTC, faisal-alvi approved these changes
@mattheu thank you for your efforts! 🚀

2023-02-03 07:14 UTC, merged