Explicitly declare global
10up/simple-local-avatars pull request #34
Opened 2019-10-11 13:39 UTC by pdewouters

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/10up/simple-local-avatars/blob/develop/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

2019-10-11 17:04 UTC, adamsilverstein requested changes
Hi @pdewouters and thanks for the PR!

Can you give some more details about why you want to make this change? 

* What exact conditions are used to create the error you show above, can you share your loading code?
* Have you considered other approaches? 
* Could this change have unintended side effects?

2019-10-14 08:48 UTC, pdewouters commented
@adamsilverstein yes here's where the plugin is loaded: https://github.com/humanmade/altis-cms/pull/111/files , we want to include it via composer, and then load it on the `plugins_loaded` action by including the plugin file manually.
The reason this error occurs is because `$simple_local_avatars` is not in the global scope when the plugin file is included via a calling function.

Other approach could be:

```
global $simple_local_avatars;
$simple_local_avatars = new Simple_Local_Avatars();
```

Instead of making it a super global with `$GLOBALS` - this might be preferable?

2019-10-18 17:32 UTC, adamsilverstein commented
@pdewouters thanks for clarifying, i'll take a closer look and let you know what we can do here.

2019-10-18 18:30 UTC, adamsilverstein commented
@pdewouters - this looks good, i verified the issue and the fix. 

can you please change to your suggested 
```
global $simple_local_avatars;
$simple_local_avatars = new Simple_Local_Avatars();
```
to better match the rest of the code

2019-10-18 18:31 UTC, adamsilverstein commented on simple-local-avatars.php
> +$GLOBALS['simple_local_avatars'] = new Simple_Local_Avatars();
```suggestion
global $simple_local_avatars;
$simple_local_avatars = new Simple_Local_Avatars();
```

2019-10-21 14:04 UTC, adamsilverstein approved these changes
Thanks @pdewouters!

2019-10-21 14:06 UTC, merged

2020-07-01 13:11 UTC, pdewouters commented
Thanks for merging @adamsilverstein , any plans for a new tagged release?

2020-07-01 15:38 UTC, jeffpaul commented
@pdewouters per https://github.com/10up/simple-local-avatars/issues/51, we're looking to release 2.2.0 sometime in July.  We've got 2 releases ahead of it on other open source projects, but hope to get to 2.2.0 soon.